### ISSUE TITLE
Foam not starting up cleanly and seeing an error pop up at startup

### ISSUE THREAD

**Issue by bijukunjummen** [foambubble/foam#982] opened 2022-04-14 15:30 UTC
### Describe the bug

Hi, I am not entirely sure which content in my workspace may be causing this behavior, I am seeing this stack trace:

```
An error occurred while bootstrapping Foam. TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator)) at Function.analyzeLink (/Users/abc/.vscode/extensions/foam.foam-vscode-0.18.1/out/core/services/markdown-link.js:15:48) at
```

this is with 0.18.1 version of foam

### Steps to Reproduce the Bug or Issue

This happens at the load time of foam, if I open vscode, everything appears to load up but then none of links work - `[[a link]]`
and seeing this message logged:
```
An error occurred while bootstrapping Foam. TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator)) at Function.analyzeLink (/Users/abc/.vscode/extensions/foam.foam-vscode-0.18.1/out/core/services/markdown-link.js:15:48) at
```

### Expected behavior

Foam should load up cleanly, and links should work

### Operating System Version

macOS

### Visual Studio Code Version

Version: 1.66.2. Foam version 0.18.1

**Comment by dylan-k** [comment] 2022-04-14 17:36
see also: #974 and #975

**Comment by bijukunjummen** [comment] 2022-04-14 18:34
I think I am able to replicate now. Feels different from #974, #975, it happens with links which look like this:

```
[](somelink)
```

Adding in a description or a valid protocol appears to fix it though.
```
[Test](somelink)
```

```
[](http://somelink)
```

**Comment by riccardoferretti** [comment] 2022-04-15 07:04
This should be fixed in 0.18.2, can you check?

**Comment by spectereye** [comment] 2022-04-15 07:21
not solved in 0.18.2, i met the same error with 0.18.2 while works fine in weeks ago maybe 0.17.x

**Comment by riccardoferretti** [comment] 2022-04-15 12:58
Yup, we changed some things in the way links are processed in 0.18, that's the cause of the issue.
Can you provide more context? A small repo to reproduce the issue would be the best. Also a full stack trace of the error would help.
My guess is that there is a link in a format that is not properly matched, which is causing the issue.

**Comment by spectereye** [comment] 2022-04-16 04:22
@riccardoferretti  thanks and for quick reply! my exception gotten:
```
An error occurred while bootstrapping Foam. TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
	at Function.analyzeLink (my\vscode\data\extensions\foam.foam-vscode-0.18.2\out\core\services\markdown-link.js:16:48)
	at MarkdownResourceProvider.resolveLink (my\vscode\data\extensions\foam.foam-vscode-0.18.2\out\core\services\markdown-provider.js:79:66)
	at FoamWorkspace.resolveLink (my\vscode\data\extensions\foam.foam-vscode-0.18.2\out\core\model\workspace.js:130:33)
	at FoamGraph.update (my\vscode\data\extensions\foam.foam-vscode-0.18.2\out\core\model\graph.js:84:50)
	at Function.fromWorkspace (my\vscode\data\extensions\foam.foam-vscode-0.18.2\out\core\model\graph.js:68:15)
	at Object.exports.bootstrap (my\vscode\data\extensions\foam.foam-vscode-0.18.2\out\core\model\foam.js:16:37)
```
this only occur in one big notebook (1000+ files with folders), so hard for me to find which file caused this error.
this notebook use `wikilinks` and special chars, so i test to made another small new notebook with `wikilinks` and special chars but works fine.

Any log info. on console so we can check which notebook file caused this?

**Comment by bijukunjummen** [comment] 2022-04-16 15:32
> This should be fixed in 0.18.2, can you check?
Yes, this actually fixes my issue - `[](somelink)` type links work now.

**Comment by riccardoferretti** [comment] 2022-04-17 16:49
@spectereye releasing now 0.18.3 with better error reporting.
Also, failed link resolution will no longer block the full graph computation, which means your bootstrap should go through now, so please check the Foam logs (see https://github.com/foambubble/foam/blob/master/docs/features/foam-logging-in-vscode.md)

**Comment by spectereye** [comment] 2022-04-18 06:48
@riccardoferretti  thanks a lot! tried 0.18.3, everything works fine now.
the issue was caused by a bad link, and the new log report it clearly and doesn't stop other notes as expected.
Nice work!
```
[error - 2:42:17 pm] Error while resolving link <file:///C:/Users/cnshflu/Documents/My> in C:\Felix\office_notebook\notebook_it\delayed_expansion_in_batch.md, skipping.
{
  "type": "link",
  "rawText": "<file:///C:/Users/cnshflu/Documents/My>",
  "range": {
    "start": {
      "line": 280,
      "character": 5
    },
    "end": {
      "line": 280,
      "character": 44
    }
  }
}
"Error: Couldn't parse link <file:///C:/Users/cnshflu/Documents/My> - TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))\n\tat Function.analyzeLink (c:\\Felix\\office_app\\vscode\\data\\extensions\\foam.foam-vscode-0.18.3\\out\\core\\services\\markdown-link.js:27:19)\n\tat MarkdownResourceProvider.resolveLink (c:\\Felix\\office_app\\vscode\\data\\extensions\\foam.foam-vscode-0.18.3\\out\\core\\services\\markdown-provider.js:79:66)\n\tat FoamWorkspace.resolveLink (c:\\Felix\\office_app\\vscode\\data\\extensions\\foam.foam-vscode-0.18.3\\out\\core\\model\\workspace.js:130:33)\n\tat FoamGraph.update (c:\\Felix\\office_app\\vscode\\data\\extensions\\foam.foam-vscode-0.18.3\\out\\core\\model\\graph.js:85:54)\n\tat Function.fromWorkspace (c:\\Felix\\office_app\\vscode\\data\\extensions\\foam.foam-vscode-0.18.3\\out\\core\\model\\graph.js:68:15)\n\tat Object.exports.bootstrap (c:\\Felix\\office_app\\vscode\\data\\extensions\\foam.foam-vscode-0.18.3\\out\\core\\model\\foam.js:16:37)"
[
```

**Comment by riccardoferretti** [comment] 2022-04-18 20:35
Great! Glad it worked out!

**Closed by riccardoferretti** 2022-04-18 20:35 UTC
