### ISSUE TITLE
The code indicates that an error has occurred and that a non-existent anchor point is present

### ISSUE THREAD

**Issue by fanlushuai** [foambubble/foam#947] opened 2022-02-28 09:24 UTC
Listen for vscode to delete files and update anchor index

**Comment by riccardoferretti** [comment] 2022-02-28 12:52
Hi @fanlushuai can you clarify what issue you have encountered and how to reproduce it?

**Comment by fanlushuai** [comment] 2022-02-28 18:13
@riccardoferretti 
![动画](https://user-images.githubusercontent.com/21078607/156035714-f59adf81-f60a-4f0c-ba05-e21ea814f8a2.gif)

This describes a file that does not exist, but the anchor point is indicated in a later code prompt. This can make it difficult for users to detect errors they may have made

**Comment by riccardoferretti** [comment] 2022-03-02 13:51
Hi @fanlushuai, this is a feature, not a bug ;)

We call them placeholders (see the panel on the left of your screen).
It's a way to create nodes in the knowledge base without creating content for them.
You can see they are also shown in the graph.

I will close this issue, but let me know if something is still unclear

**Closed by riccardoferretti** 2022-03-02 13:51 UTC

**Comment by fanlushuai** [comment] 2022-03-02 19:53
Seems to understand.

But there's a problem



How to distinguish between creating a new node and referencing an existing node



In the use of code hints

**Comment by riccardoferretti** [comment] 2022-03-03 10:04
They are highlighted in different ways, and the tooltip when hovering in the link will tell you if it's one or the other
