### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by lautjy-caruna** [foambubble/foam#651] opened 2021-05-23 06:28 UTC
- Issue Type: `Performance`
- Extension Name: `foam-vscode`
- Extension Version: `0.13.3`
- OS Version: `Windows_NT x64 10.0.21382`
- VS Code version: `1.56.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`[foam.foam-vscode-unresponsive.cpuprofile.txt](https://github.com/foambubble/foam/files/6527633/foam.foam-vscode-unresponsive.cpuprofile.txt)`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by riccardoferretti** [comment] 2021-05-23 10:42
duplicate of #626

**Closed by riccardoferretti** 2021-05-23 10:42 UTC
