### ISSUE TITLE
Foam v0.25.9 very slow

### ISSUE THREAD

**Issue by ktrNozomi** [foambubble/foam#1345] opened 2024-03-17 23:36 UTC
### Describe the bug

When in Vim mode (either Vim extension or VSCode Neovim extension), enter `:w` to save the current editing file, and the file will not respond to any key strokes.

I uninstalled Foam extension, the problem doesn't exist.
I returned back to Foam v0.25.8, the problem doesn't exist.

### Steps to Reproduce the Bug or Issue

See the bug description.

### Expected behavior

After saving the file, the editor should respond to key strokes normally.

### Operating System Version

Windows 11

### Visual Studio Code Version

1.87.2 User mode

**Comment by riccardoferretti** [comment] 2024-03-18 09:07
Thanks for reporting the issue, I will push the fix right away (silly bug)

**Comment by riccardoferretti** [comment] 2024-03-18 09:10
I just pushed v0.25.10 - let me know if you are still experiencing the problem. Will close the issue if the problem is gone

**Comment by riccardoferretti** [comment] 2024-03-18 09:46
Can you check what happens if you revert to 0.25.8 ? Does that solve the issues you are having?

**Comment by ktrNozomi** [comment] 2024-03-18 10:15
@riccardoferretti after updating to v0.25.10, the key stroke responds normally; but I see as @ais said, the same situation happens to me -- the CPU increased to 30% after saving the file. But this doesn't influence the fluency on my machine, my CPU is AMD R7 5850U.

**Comment by riccardoferretti** [comment] 2024-03-18 10:33
@ktrNozomi can you also do the comparison with 0.25.8? Just wanna be sure that in the meantime something hasn't changed in VS Code that instead seems related to the extension (this happened in the past).
Can you and @ais please:
1. check the current state with 0.25.10
2. revert the extension to 0.25.8
3. compare the resource utilization
4. let us know :)

I am saying this because, beside the bug I introduced, the changes should not have performance implications. There might be another more subtle bug, looking into it

**Comment by ktrNozomi** [comment] 2024-03-18 10:41
@riccardoferretti after testing, it seems that both v0.25.8 and v0.25.10 have performance issues

This is v0.25.10:
![v0 25 10](https://github.com/foambubble/foam/assets/86712470/829b0ec8-b163-4f7a-adc6-b84477dde638)

This is v0.25.8
![v0 25 8](https://github.com/foambubble/foam/assets/86712470/4b42ca1a-0492-4493-a1b9-d75bf6e9369c)

**Comment by ktrNozomi** [comment] 2024-03-18 10:45
@riccardoferretti after testing, it seems that v0.25.8 has no problem and v0.25.10 has performance issue.

This is v0.25.8:
![v0 25 8](https://github.com/foambubble/foam/assets/86712470/3d93dbf2-2693-4b25-b8f2-ba4021f8e58b)

This is v0.25.10:
![v0 25 10](https://github.com/foambubble/foam/assets/86712470/2b828793-5219-4366-a4f7-ca6861c39e34)

**Comment by riccardoferretti** [comment] 2024-03-18 11:07
Ok thx, will look into it

**Comment by riccardoferretti** [comment] 2024-03-18 12:19
Ok, I think I have found the actual problem and pushed 0.25.11 which should have addressed it.
@ais @ktrNozomi can you please let me know if things get better?

**Comment by ktrNozomi** [comment] 2024-03-18 13:05
> Ok, I think I have found the actual problem and pushed 0.25.11 which should have addressed it. @ais @ktrNozomi can you please let me know if things get better?

Thanks a lot for your work! Now everything works fine on my machine. Thanks @ais too for finding bugs!

**Comment by riccardoferretti** [comment] 2024-03-18 13:22
Thank you both for bringing it up to my attention, cheers!

**Closed by riccardoferretti** 2024-03-18 13:22 UTC
