### ISSUE TITLE
subdirectory notes have inconsistent behavior

### ISSUE THREAD

**Issue by josephhardinee** [foambubble/foam#747] opened 2021-08-19 18:01 UTC
- Foam version: 
- Platform: Windows
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
This seems to have recently broke but on windows if using a link like [[dir/mynote]] it works the first time you click it and creates the note. The second time you click however it tries to create a new note in the same spot, which fails because the note already exists. If you change it to [[dir\mynote]] on windows it does work as expected (But I imagine would break on a mac making cross platform notes hard. 

**Steps to reproduce**
1. On windows create a [[dir/mynote]], ctrl-click, , save, then ctrl click the link again. 

I've tried janitor, and update markdown references as well and that has no impact.

**Comment by josephhardinee** [comment] 2021-09-02 00:24
Note I tried this on mac and have the same issue, except changing the directionality on the slash doesn't work. The first link gets created in the right place, but links after that do not.

**Comment by leonvisscher** [comment] 2021-09-02 17:05
@josephhardinee 
What does it say when you hover the link in VSCode? For me it says something like: "Create note for '/path/to/note/file.md'".

**Comment by josephhardinee** [comment] 2021-09-02 17:36
Same on mine
![image](https://user-images.githubusercontent.com/761704/131890668-87c0269d-7d6d-4ec7-bc21-be51d2c42556.png)
then if I cmd-click it:
![image](https://user-images.githubusercontent.com/761704/131890771-ca6b1ebf-3350-47dd-b49d-845f868072f7.png)
But the file does already exist if I try to click create.

**Comment by kalingibbons** [comment] 2021-09-06 18:01
I'll add that simply hovering over the newly written wikilink will create a new file with `/`s removed, and in the wrong location. Using ctrl+click, F12, or another goto-definition method will all do the same. The only way I can get the note created in the correct directory is by clicking the _Create notes for 'directory_x/note_y'_ link in the hover prompt, all keyboard methods are off the table.

![image](https://user-images.githubusercontent.com/11838956/132250734-74b99e36-a0c2-4262-9756-57063e553ee7.png)
An image showing the newly created (but incorrectly located/named) file in the explorer, just by ctrl+hover on the wikilink (powertoys screenshot removed the cursor).

**Comment by pderaaij** [comment] 2021-09-08 19:17
To be sure, is the extension `markdown-notes` installed? This used to be recommended, but after the last releases this extension interferes with the behaviour of Foam, or the other way around of course :)

**Comment by kalingibbons** [comment] 2021-09-10 16:15
Yes, I had it installed. Uninstalling `markdown-notes` results in the same behavior as above, but now goto-definition hotkeys won't work for previously created notes. I have to use the hover to interact with any wikilinks.

**Comment by omo** [comment] 2021-11-07 13:37
+1. Overriding "go-to definition" would be much appreciated.
 Supporting "go-to definition" or some kind of keyboard shortcut much appreciated.

Looking at [markdown-note](https://github.com/kortina/vscode-markdown-notes/), what should be done is probably providing a [DefinitionProvider](https://code.visualstudio.com/api/language-extensions/programmatic-language-features
) of markdown.

For a workaround. I assigned a key binding to "Open Link" command, but using "go-to definition" is better since it doesn't waste the precious real estate in the key binding land.

**Comment by riccardoferretti** [comment] 2021-11-10 11:27
@kalingibbons @omo definitions are coming - https://github.com/foambubble/foam/pull/821

**Comment by michael-guimet** [comment] 2021-11-19 18:11
- Foam version: **v0.15.6**
- VS Code version: **1.62.3**
- Platform: **Windows 11** 
- Issue occurs on the [foam template](https://github.com/foambubble/foam-template) repo: **Yes**

**Summary**
Cannot follow subdirectory links with Ctrl+click in editor mode

**Steps to reproduce**
1. Download  [foam template](https://github.com/foambubble/foam-template)
2. Look at docs/principles.md in editor (not preview)
3. On line 39, ctrl+click on the [[recommended-extentions]] link. 
4. Bug: Expected behaviour is opening of existing file "docs/recommended-extentions.md". Note this file is in the subdirectory docs and in the same directory as principles.
6. On line 39, ctrl+click on the [[recipes]] link.
7.  Bug: Expected behaviour is opening of existing file "docs/recipes/recipes.md". Note this file is in the subdirectory docs and in a different directory as principles.
8. Note this does not happen at top level directory (to test this you can create a top level directory file and link it in the readme.md, for example. Behaviour is as expected)

**Additional information**

Additionally (needs hover popup preview enabled):

8. On line 39, hover over [[recommended-extentions]] link. 
9. See above preview the message: "Create note for /c:/path/to/directory/foam-master/docs/recommended-extensions.md'' (ctrl+click)" 
10. Bug: Note that the "recommended-extensions.md" file already exists at the described directory.
11. Note the strange "/" in front of the path (might be normal, but I found it strange)

Additionally:

- I did not encounter this problem until recently (probably one of the last couple releases)

**Comment by riccardoferretti** [comment] 2021-12-02 16:54
My guess is that this is addressed in 0.16.x - can a Windows user validate please?

**Comment by michael-guimet** [comment] 2021-12-02 20:20
I can confirm this is fixed.

**Comment by riccardoferretti** [comment] 2021-12-03 00:07
thanks @michael-guimet

**Closed by riccardoferretti** 2021-12-03 00:07 UTC
Labels: bug
