### ISSUE TITLE
Can't generate wikilinks

### ISSUE THREAD

**Issue by zzan1** [foambubble/foam#390] opened 2020-11-29 08:01 UTC
- Foam version: 0.7.2

**Summary**

![image](https://user-images.githubusercontent.com/47623989/100536475-cf85d780-325b-11eb-887b-12e794199415.png)

cant generate wikilinks as picture. I have tried the command `foam: update markdown reference list`. No debug massage founded in VScode. 

**Steps to reproduce**
1.
2.

Does this issue occur on the [foam template](https://github.com/foambubble/foam-template) repo? Yes/No
Yes
**Additional information**

*Feel free to attach a screenshot and/or include a zip with a minimal repo to reproduce the issue*

**Comment by SanketDG** [comment] 2020-11-29 09:42
I am assuming that these references with underscores `[[sample_note]]` are actually `sample-note.md` in the filesystem? This is where the mismatch occurs, because the file has to be `sample_note.md` because that's the right slug conversion of `[[sample_note]]`, or it has to be referenced like `[[sample note]]` or `[[Sample Note]]` or `[[sample-note]]`.

**Comment by zzan1** [comment] 2020-11-29 12:11
1.  the filesystem is:
![image](https://user-images.githubusercontent.com/47623989/100541445-f7d2fd80-327e-11eb-9b7e-b4c698f8d1bd.png)

**Comment by SanketDG** [comment] 2020-11-29 13:31
Is https://github.com/zzan1/FoamNoteLib.git the right repo to inspect in this case? I just took a look at that and it seems like the references generate for me, even though there are other bugs in the references generation.

**Comment by zzan1** [comment] 2020-11-29 13:54
yean， it worked yesterday, but today, it is broken. And I push the newest version. are you comfortable to check it.

**Comment by SanketDG** [comment] 2020-11-29 14:01
The references do generate for me:

**Comment by SanketDG** [comment] 2020-11-29 14:04
The references do generate for me, maybe this bug is something related to windows?

The link `[[ebl-parameters]]` seem to not link for me on Github (maybe because of spaces in the leading folder?)

```
[//begin]: # "Autogenerated link references for markdown compatibility"
[Low reflective index decrement]: Diamond_grating/low-reflective-index-decrement "Low Reflective Index Decrement"
[sputter]: Diamond_grating/sputter "Sputter"
[fib]: Diamond_grating/fib "FIB"
[ebl]: Diamond_grating/ebl "EBL Setup"
[chromium and oxgen plasma]: Diamond_grating/chromium-and-oxgen-plasma "chromium-and-oxgen-plasma"
[ebl parameters]: EBL & FIB/ebl-parameters "Ebl Parameters "
[hard-mask-diamond]: Diamond_grating/hard-mask-diamond "Hard Mask Diamond"
[icp-rie]: Diamond_grating/icp-rie "ICP-RIE"
[tapered structure]: Diamond_grating/tapered-structure "Tapered Structure"
[fluctuation_of_shot_to_shot]: FELs/fluctuation_of_shot_to_shot "Shot-to-shot fluctuations"
[behavior_of_seed_electron]: FELs/behavior_of_seed_electron "Behavior of seed electron"
[transmissive-spectrometer-design]: SpctrometerDesing/transmissive-spectrometer-design "Transmissive Spectrometer Design"
[//end]: # "Autogenerated link references"
```

**Comment by petermllrr** [comment] 2020-12-01 10:35
Having the same issue here. Worked yesterday, stopped working out of a sudden. Did not install any extra extension and tested with a fresh template repo.

**Comment by keremkayabay** [comment] 2020-12-01 14:39
In my case, wikilinks are only generated for new files. And they are gone after I close and reopen VSCode (not reload though).

OS: Windows 10, working in a workspace.

**Comment by jesusnunezpro** [comment] 2020-12-01 18:52
I just tested today by creating a new repo from the template and when I hit save it removes the links from **inbox.md**.
Running on vscode 1.51.1/Windows 10 19041

**Comment by jesusnunezpro** [comment] 2020-12-02 01:08
> In my case, wikilinks are only generated for new files. And they are gone after I close and reopen VSCode (not reload, though).
> 
> OS: Windows 10, working in a workspace.

Same thing happens on my environment, not sure if it's caused by the same issue or is a different issue altogether.

**Comment by jesusnunezpro** [comment] 2020-12-02 01:19
Tested by reverting to version 0.6.0 and it still doesn't work... I wonder if it's an issue with vscode and not Foam

**Comment by jesusnunezpro** [comment] 2020-12-02 01:29
If I clone the repo to my WSL2 environment and open that from vscode... then there is no issue... something about running it from Windows file system

**Comment by AndrewNatoli** [comment] 2020-12-02 05:10
I'm seeing this on MacOS.

![image](https://user-images.githubusercontent.com/4162073/100830864-9e133480-3432-11eb-9e24-d10e3397a4c8.png)

Reference section is not added to `cat-food.md`. It _did_ make a link on the graph to `cheese_underscore` but there's actually a _second_ node added (see right of "Cat Food") that actually represents the file; it has the proper label and all.

**Comment by jesusnunezpro** [comment] 2020-12-21 14:29
I tested the automatic link generation today with VSCode 1.51.1 and Foam Extension 0.7.6 and it worked on Windows. ¯\_(ツ)_/¯

**Comment by riccardoferretti** [comment] 2020-12-21 15:49
The latest patch versions of Foam addressed various Windows-related issues, so that was probably the cause of the issues here.

In this case I will close the issue now as I believe nothing else needs to be tracked here

**Closed by riccardoferretti** 2020-12-21 15:49 UTC
Labels: bug
