### ISSUE TITLE
Wikilinks, Links and tags inside (inline) code blocks should be ignored

### ISSUE THREAD

**Issue by ysl2** [foambubble/foam#373] opened 2020-11-25 02:52 UTC
**Describe the bug**

If you define a inline-code `'[[file2]]'` in file1.md, and unfortunately there is a file `file2.md` in your repository, Foam will regard the inline-code as a link, and will appears in `file2.md`'s "backlink" interface,  this fake-link also can be opened

**To Reproduce**

You can reproduce it by folling these steps:
1. Create a file `file1.md`
2. Create a file `file2.md`
3. Type these words in `file1.md` :

```
`[[file2]]`
```

**Expected behavior**
`'[[file2]]'` will be regarded as a link, and a backlink in `file2.md` will appear in "backlink" interface

**Screenshots**

![image](https://user-images.githubusercontent.com/39717545/100176843-f6ff3c00-2f0b-11eb-82ca-90da3623329f.png)
![image](https://user-images.githubusercontent.com/39717545/100177045-40e82200-2f0c-11eb-8495-802feb62f27c.png)

Supplement:

After posting this issue, I tested the code-block, the result is same with inline-code, and if `file2.md` doesn't exist, Foam will create it.

I'm not sure if this is a bug or what you want, I mean, not "auto create file", but "`inline-code`/`code blocks` as a link". But what I can make sure is I can't open this fake-links in preview mode.

**Comment by riccardoferretti** [comment] 2020-11-25 12:44
This is not currently managed by Foam itself, but https://github.com/kortina/vscode-markdown-notes.
I am not sure whether the behavior is desired.

I agree that probably anything inside a code block or inline code block should not be included in the parsing of links/wikilinks (or tags for that matter, and I am pretty sure we currently include those).

**Comment by Kcalb35** [comment] 2021-05-02 06:55
I also ran into this bug when I was writing c++ in code blocks. 
I found that '#include' or '#define' or other macro in c/c++ were recognized as tag marks. It is quite annoying.

My c++ code block is shown below.
![Screenshot_20210502_145102](https://user-images.githubusercontent.com/56818040/116805008-e9eb1680-ab55-11eb-8b86-45d73e559a6d.png)

And my tag panel which was 'polluted' by c/c++ macro is shown below.
![Screenshot_20210502_145004](https://user-images.githubusercontent.com/56818040/116804979-b60ff100-ab55-11eb-8981-1f5a57ad5c71.png)

**Comment by MCluck90** [comment] 2022-01-02 03:43
I just did some quick testing to see if this was still a problem. I'm unable to reproduce the issue now that backlinks and tags are handled by Foam itself. I believe this issue can be closed

**Comment by riccardoferretti** [comment] 2022-11-13 22:30
Yup this has been fixed a long time ago and forgot to close the issue :)

**Closed by riccardoferretti** 2022-11-13 22:30 UTC
Labels: bug, foam-vscode
