### ISSUE TITLE
["BUG"] Title Max Length not applied to Placeholder Notes in the Graph

### ISSUE THREAD

**Issue by fmagin** [foambubble/foam#376] opened 2020-11-25 18:34 UTC
**Describe the bug**

The setting for the `Title Max Length` is not used for the placeholder nodes for links where the target note does not exist yet.

**To Reproduce**

Create a file with content like:
```
# Bug Demo

[[Existing note with a very long title]]

[[Nonexistant note with a very long title that should be cut off]]
```
Then create the first note (e.g. by clicking on the link)

Now open the Foam Graph to get the result like in the screenshot

**Screenshots**

![image](https://user-images.githubusercontent.com/8415354/100268100-cb547400-2f54-11eb-92f8-bfe946b240c3.png)

**Expected behavior**

Titles of nonexistant notes to be shortened like other titles.

**Comment by jmg-duarte** [comment] 2020-11-26 20:45
I just tried to reproduce the issue and it works for me, I reckon however it may have to do with settings.
Could you share yours?

**Comment by riccardoferretti** [comment] 2020-11-26 21:15
@jmg-duarte did you try with a link not pointing to an existing note?
I think atm we only cut the title of the result from `getNotes`, which doesn't include the placeholders

**Comment by jmg-duarte** [comment] 2020-11-26 21:21
I did, and it worked

**Comment by riccardoferretti** [comment] 2020-11-26 21:36
Looking at the code, I think the issue is in https://github.com/foambubble/foam/blob/168ef5edb4ad1d2b185e19c773b58c6393078d39/packages/foam-vscode/src/features/dataviz.ts#L61
but we don't do the same for placeholders in https://github.com/foambubble/foam/blob/168ef5edb4ad1d2b185e19c773b58c6393078d39/packages/foam-vscode/src/features/dataviz.ts#L69

**Comment by jmg-duarte** [comment] 2020-11-26 22:30
I'll test and PR

**Comment by jmg-duarte** [comment] 2020-11-26 22:36
Moving further discussion to the PR and closing the issue

**Closed by jmg-duarte** 2020-11-26 22:36 UTC
Labels: bug
