### ISSUE TITLE
Bug report: Foam: Show graph command not showing normal markdown []() links

### ISSUE THREAD

**Issue by DrakeWhu** [foambubble/foam#420] opened 2020-12-30 00:08 UTC
- Foam version: 0.7.1
- Platform: Windows 10
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: No

**Summary**
Normal markdown `[Title](document.md)` links are not showing on `Foam: Show Graph` command

**Steps to reproduce**
1. Create two bubbles and link them with `[Title](document.md)`
2. Open the console and type `Foam: Show Graph`

**Additional information**
It seems using an extension called md-graph solves the problem

**Comment by riccardoferretti** [comment] 2020-12-31 11:22
duplicate of #299

**Closed by riccardoferretti** 2020-12-31 11:22 UTC
Labels: bug
