### ISSUE TITLE
Changes in daily notes settings are not immediately applied

### ISSUE THREAD

**Issue by taydotis** [foambubble/foam#484] opened 2021-02-10 21:19 UTC
- Foam version: v0.9.1
- Platform: Mac
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**

I have set some custom parameters for my daily notes, but these parameters are not carried over for the quick snippets provided on [daily-notes.md](https://github.com/foambubble/foam-template/blob/master/docs/features/daily-notes.md) page.

For instance, my `foam.openDailyNote.directory` is set to `dailies`, and my daily note is automatically created in this directory as intended when I press `alt+d`. However, typing in `/today` or `/tomorrow` generates notes in the default `journal` subdirectory instead of linking to my custom directory.

Additionally, the header does not match my set `titleFormat`, which again works as intended with the `alt+d` shortcut. I imagine this is the case for all the `foam.openDailyNote` properties, but I did not test the rest.

**Comment by taydotis** [comment] 2021-02-10 21:27
Ah, closing and reopening VSCode fixed the issue. Perhaps some kind of caching thing?

I guess the shortcut works immediately but the snippets need a refresh to get the proper settings loaded. Anyways, probably worth disregarding.

**Comment by riccardoferretti** [comment] 2021-02-11 10:06
Thanks for reporting this @taydotis, I believe the issue is that we are not listening for changes in those configuration settings, which we should

**Comment by riccardoferretti** [comment] 2022-03-21 14:21
Closing now as the recommended way of achieving this would be to use the `daily-note.md` template

**Closed by riccardoferretti** 2022-03-21 14:21 UTC
Labels: bug, foam-vscode
