### ISSUE TITLE
Changing a file name does not update backlinks

### ISSUE THREAD

**Issue by antistic** [foambubble/foam#305] opened 2020-10-29 13:33 UTC
Consider a file

```
# File 1

Link to [[File 2]]
```

If you rename `file-2.md`, there is no prompt to update backlinks in file 1. This is something Obsidian supports, and VSCode supports this for other relative links like javascript imports.

I looked to see if there was VSCode support for this, but [they labelled it as an extension candidate](https://github.com/microsoft/vscode/issues/92922), and even if they did add it I don't know if that would work for WikiLinks.

**Comment by riccardoferretti** [comment] 2020-10-29 15:52
thx @ant-i-c-s, support for refactoring is on the roadmap, will be coming soon

**Comment by ErikPlachta** [comment] 2020-11-23 01:08
What I'm finding is that it wont even let you change backlinks manually. It updates with the old file name.
-Am I right that the only option ATM is delete and create a new file or have a broken backlink?

**Comment by riccardoferretti** [comment] 2020-11-23 12:14
@ErikPlachta the second problem should have been addressed by #349, do you have this issue with Foam 0.6.0?

**Comment by ErikPlachta** [comment] 2020-11-24 03:12
@riccardoferretti - I'm embarrassed to say I don't know how to check. 😳  I just started playing with Foam yesterday and learning how it works.

Thinking I'm going to export my notes, burn it down, and build it back up vs wasting time.

**Comment by ysl970629** [comment] 2020-11-24 03:45
I was wondering if it would also be possible to automatically update backlinks when moving files?

**Comment by riccardoferretti** [comment] 2020-11-24 19:42
@ErikPlachta check in your extension tab:

![image](https://user-images.githubusercontent.com/457005/100143394-8ddce180-2e95-11eb-9ca2-115e9430c615.png)

@ysl970629 it will most definitely be possible 👍

**Comment by ErikPlachta** [comment] 2020-11-24 19:44
Confirmed on 0.6.0

**Comment by riccardoferretti** [comment] 2020-11-24 19:50
you mean the bug is still there in 0.6.0?

**Comment by ErikPlachta** [comment] 2020-11-26 00:32
@riccardoferretti  said,  "_you mean the bug is still there in 0.6.0?_"

Yes, that is correct. I'm going to read through the documentation tonight and see if I'm breaking a rule somewhere I don't realize it. 

For context, here is a photo of code next to preview view. 
> Red line on right to point out the garbage info from broken back-links for file names I've changed after foam auto-created them.

![image](https://user-images.githubusercontent.com/17508965/100294368-95af8b00-2f54-11eb-8014-689c00391e84.png)

**Comment by ysl970629** [comment] 2020-11-26 01:18
A plugin can update the regular markdown links`[]()`, I know it maybe not relative to this issue... I just want you know there is a plugin which can update `[]()`, and I think if it could help you a bit @riccardoferretti

**Comment by riccardoferretti** [comment] 2020-11-26 19:01
thx @ErikPlachta  @ysl970629  
a major piece of work on linking is happening soon, this will be part of it

**Comment by ErikPlachta** [comment] 2020-11-26 19:05
No problem, love it and will keep using it. 

I made a clean clone and disabled all extension except for required and verified issue still happening.

- **Should I make a bug report or anything else I can do to help? **

**Comment by riccardoferretti** [comment] 2020-11-26 21:41
thanks @ErikPlachta this issue will track the file renaming, which actually is totally decoupled from the improvements on the linking side - it will just be more precise once we the linking gets more robust

**Comment by ainar** [comment] 2021-05-18 19:27
Do you have any information on how you plan to implement the refactoring, just to know where we can help?

**Comment by riccardoferretti** [comment] 2021-05-20 09:17
the approach I am thinking of atm is along the following flow:

1. a file is renamed
2. the watcher notified the `FoamWorkspace`
3. the workspace/graph looks for connections to the existing file from other files
4. the wikilinks are updated and the files saved 

there are still a few open questions (e.g. how to handle files that are currently opened in a tab witihin VS Code)

**Comment by riccardoferretti** [comment] 2021-12-03 00:07
closing as duplicate of #809 - moving the conversation there

**Closed by riccardoferretti** 2021-12-03 00:07 UTC
Labels: foam-core
