### ISSUE TITLE
When creating the files with cmd+click, if the wikilink includes some special characters (:, ó, etc), it dosen't detect the file is created

### ISSUE THREAD

**Issue by JuanLucha** [foambubble/foam#918] opened 2022-01-21 17:51 UTC
- Foam version: v0.17.3
- Platform: Mac
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: No?

**Summary**
When creating the files with cmd+click, if the wikilink includes some special characters (:, ó, etc), it dosen't detect the file is created. So, it always appears as a placeholder instead of a link.

**Steps to reproduce**
1. In any file (let's call it `index.md`) write a wikilink with some special character like `:` or `ó`. Example: `[[Juego: Maratón]]`
2. Do cmd+click over the wikiling. You will be taken to the file `Juego: Maratón.md` file.
3. go back to `index.md` and see how `[[Juego: Maratón]]` has the color scheme for place holders instead of link, like not detecting the file `Juego: Maratón.md` is already created.
4. (Extra) If you cmd+click on Maratón after that, a `Maratón.md` file will be created, which shouldn't be there as the link is not [[Maratón]] but [[Juego: Maratón]].

**Additional information**
This only happens when link reference generation is on. I have it on with extensions.
If I remove the link references, everything seems ok (even the navigation following the link):
![Captura de pantalla 2022-01-21 a las 18 50 29](https://user-images.githubusercontent.com/3832570/150575851-f305acae-1904-4a21-9a4a-b924ee044d34.png)

But if I generate the links for markdown compatibility, then the wikilink containing the special characters breaks and the navigation fails:
![Captura de pantalla 2022-01-21 a las 18 50 39](https://user-images.githubusercontent.com/3832570/150575945-339d161b-7e10-4580-88e0-43d2b7539585.png)

**Comment by ChangChen-Walt** [comment] 2022-01-22 19:27
I also found it was bugged when I tried to create a note with a single quote mark in the file title.

**Comment by ChangChen-Walt** [comment] 2022-01-22 19:30
I also found it was bugged when I tried to create a note with a single quote mark in the file title,
such as the intended file name as [[Slutsky's_Thm]].
Neither the 'cmd + click' nor the 'Foam: Create New Note' command work

**Comment by riccardoferretti** [comment] 2022-11-13 22:22
I just tried to reproduce this but without success, maybe it was fixed incidentally by one of the releases this year. I will close for now, feel free to try and let me know if you still experience the bug

**Closed by riccardoferretti** 2022-11-13 22:22 UTC
Labels: bug

**Comment by riccardoferretti** [comment] 2022-12-21 21:02
I just tried to reproduce it without success, are you on Windows or Mac?

**Comment by ene-wall** [comment] 2022-12-22 12:45
I'm on macOS 13.1 (22C65)

**Comment by ene-wall** [comment] 2022-12-30 12:57
@riccardoferretti are you on Windows? Do you need more information?

**Comment by riccardoferretti** [comment] 2023-01-02 17:13
I am on Mac but I can't reproduce the issue 🤷‍♂️

**Comment by ene-wall** [comment] 2023-01-05 13:22
To be honest, now it works also for me. At least I can't reproduce it anymore. Not sure what changed...
Thanks
