### ISSUE TITLE
Unable to disable IntelliSense in VS Code for Markdown

### ISSUE THREAD

**Issue by cmbail** [foambubble/foam#910] opened 2022-01-14 17:42 UTC
I don't want word completion (IntelliSense) for Markdown files in Visual Studio Code. I followed the instructions at https://stackoverflow.com/questions/38832753/how-to-disable-intellisense-in-vs-code-for-markdown and the setting is being honored for plaintext files, but not for markdown. I presume because one of the Foam or Foam-recommended extensions is overriding the flag.

Do you know which extension and is there a way to disable IntelliSense in the extension settings?

**Comment by riccardoferretti** [comment] 2022-01-15 16:28
Foam will provide autocompletion for links and tags.

I am not sure I understand if you are referring to this or not (if so: it's a feature, not a bug ™️  😅 )
To test if your problem is caused by Foam (or any other extension) please disable it and check.

I will close this for now, if through your testing you discover that Foam is in some ways causing an unexpected behavior feel free to comment here, and I can reopen the task.

**Closed by riccardoferretti** 2022-01-15 16:28 UTC

**Comment by igor-kupczynski** [comment] 2024-01-26 12:33
I'm not sure exactly what @cmbail had in mind, but I personally don't like autocompletions when writing markdown:
<img width="649" alt="Screenshot 2024-01-26 at 13 28 31" src="https://github.com/foambubble/foam/assets/166651/5f98bbfc-acdf-4a37-908a-970b8616b017">

Of course, I still want _wiki link_ autocompletions, etc. Just not _word_ autocompletion because I feel it's very distracting.

What seems to work is to have this in the workspace config:
```json
{
  "[markdown]": {
    "editor.quickSuggestions": {
      "other": false,
      "comments": false,
      "strings": false
    }
  },
..
}
```

I'm not bothered with the word autocompletion, but the link autocompletion is still there:
<img width="748" alt="Screenshot 2024-01-26 at 13 32 21" src="https://github.com/foambubble/foam/assets/166651/39982537-823f-46b4-8ab5-e2273a0a432d">


I'm new to foam though, there maybe some unintended consequences that I'm not aware of.

**Comment by riccardoferretti** [comment] 2024-01-26 13:17
Thanks for posting this, I have updated my settings to reflect what you shared.
I agree, many VS Code auto completions get in way of just writing text.
