### ISSUE TITLE
Links Not Working

### ISSUE THREAD

**Issue by Downes** [foambubble/foam#8] opened 2020-06-28 14:28 UTC
Numerous links in ReadMe.md result in a 404, eg. 'Create a single Foam workspace'.

This leaves me unable to get started with Foam - The link in 'Create a GitHub repository from foam-template. If you want to keep your thoughts to yourself, remember to set the repository private.' is broken, and the instruction is otherwise too unclear.

Sorry, I don't mean to be critical - this looks like a really interesting project - but I'm stymied at step 1.

**Comment by Downes** [comment] 2020-06-28 14:32
Problem may be the use of relative links? They are broken here https://github.com/foambubble/foam but work fine from here https://foambubble.github.io/foam/

**Comment by jevakallio** [comment] 2020-06-28 14:36
@Downes correct, the links work in VS Code and on the rendered page in GitHub pages! Apologies for the non-obvious startup experience. The links are broken on the GitHub web UI due to the way the foam-vscode link references are created without .md extension (which would break the rendered page)

This is not ideal and I have an idea of how to fix this, but it requires a fair bit of work. I'll add it to the documentation and roadmap!

**Comment by jevakallio** [comment] 2020-06-28 14:37
Closing as duplicate of #3, tracking resolution of root cause there. @Downes if you have further issues with this feature, let's continue conversation there.

**Closed by jevakallio** 2020-06-28 14:37 UTC

**Comment by jevakallio** [comment] 2020-06-28 20:16
Update: Tracking at https://github.com/foambubble/foam/issues/16
