### ISSUE TITLE
Refactor Folder Name

### ISSUE THREAD

**Issue by Alecton4** [foambubble/foam#1157] opened 2023-02-04 03:27 UTC
### Is your feature request related to a problem? Please describe.

If a folder is renamed/moved within the VSCode explorer, links containing this folder will not be updated.

Also there is no prompt for this broken link. We can only find the broken link manually.

See [the discussion](https://github.com/foambubble/foam/discussions/1153#discussioncomment-4865465)

### Describe the solution you'd like

- solution1: enable Foam to refactor folders.
- solution2: prompt for user correction whenever a broken link is detected.

### Describe alternatives you've considered

N/A

**Comment by riccardoferretti** [comment] 2023-08-23 20:22
duplicate of #1143

**Closed by riccardoferretti** 2023-08-23 20:22 UTC
