### ISSUE TITLE
Feature Request: Support for tags

### ISSUE THREAD

**Issue by sahil48** [foambubble/foam#89] opened 2020-07-11 04:37 UTC
In contrast to a heading, a tag in markdown is often created by using a `#` with no space `#tag`.

https://github.com/kortina/vscode-markdown-notes Supports this format of tags as a syntax.

By assigning a set of notes to a tag, a set of atomic notes covering a specific subject can be grouped together, and multiple tags can be added in the document to describe the subjects you would like to see with the notes shown or listed in. When hovering over a tag, a list of other documents that mention the tag in the workspace can be shown in a pop-up or peek view.

**Comment by SanketDG** [comment] 2020-07-11 08:20
Foam does have support for tags the way [Markdown Notes](https://github.com/kortina/vscode-markdown-notes) does. You should be able to do use them the way you would use tags normally. See https://github.com/kortina/vscode-markdown-notes#peek-references-to-tag

> When hovering over a tag, a list of other documents that mention the tag in the workspace can be shown in a pop-up or peek view.

Yes this would be something that is not present right now, I assume.

> a tag in markdown is often created by using a `#` with no space `#tag`

This is not necessarily true, I am pretty sure this is just a additional thing implemented by knowledge management tools and some markdown parser.


Also for publishing, writing a [transformer plugin](https://www.gatsbyjs.org/docs/creating-a-transformer-plugin/) is a great way for basic categorization of notes, basically you would create a "tag" page that would have all the pages with a certain tag. This would work well with [gatsby-digital-garden](https://github.com/mathieudutour/gatsby-digital-garden)

**Comment by mathieudutour** [comment] 2020-07-15 07:35
I believe this is a duplicate of #34

**Closed by mathieudutour** 2020-07-15 07:35 UTC
