### ISSUE TITLE
ctrl-click standard link wants to create a file 

### ISSUE THREAD

**Issue by gmccullo** [foambubble/foam#955] opened 2022-03-17 08:06 UTC
Given a valid link like this:

```md
[foobar](foobar.md)
```

When I ctrl-click "foobar.md" in the editor, I expect to navigate to foobar.md. Actual: Foam wants to create a new note.

**Comment by riccardoferretti** [comment] 2022-03-27 17:25
Can you add a repo to reproduce the issue? I seem to only be able to reproduce it for paths that have a space in them, e.g. `foo bar.md`.

**Comment by gmccullo** [comment] 2022-03-28 05:41
The next time it happens I will. But what you found already might be all there is to it, yes?

**Comment by riccardoferretti** [comment] 2022-03-28 08:25
Yup, that needs to be fixed, I was just curious to know if the problem was wider

**Comment by riccardoferretti** [comment] 2022-04-14 20:22
This should have now been fixed, I will close it - but can you check if that's the case in your set up?

**Closed by riccardoferretti** 2022-04-14 20:22 UTC
