### ISSUE TITLE
Erweiterung verursacht hohe CPU-Last

### ISSUE THREAD

**Issue by nlejus** [foambubble/foam#676] opened 2021-06-11 18:35 UTC
- Issue Type: `Performance`
- Extension Name: `foam-vscode`
- Extension Version: `0.13.7`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.58.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\nleju\AppData\Local\Temp\foam.foam-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by riccardoferretti** [comment] 2021-06-18 15:24
please update the title to english, let's make life easier for people browsing issues ;)

**Comment by fredgrott** [comment] 2021-06-22 19:15
Best translation vias my HSgwerman is: Plugin has a severe high CPU load in VsCode

**Comment by fredgrott** [comment] 2021-06-22 19:17
What would help to track down is a list of other plugins being used. Can you update the issue with your list @nlejus ?

**Comment by riccardoferretti** [comment] 2021-06-22 22:02
duplicate of #626

**Closed by riccardoferretti** 2021-06-22 22:02 UTC
