### ISSUE TITLE
When the file name contains `.` dot , Backlinking and Graph not work

### ISSUE THREAD

**Issue by EXHades** [foambubble/foam#681] opened 2021-06-16 07:23 UTC
- Foam version: v0.13.7
- Platform:  Mac
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
I try use `[[MTT6.828]]` creat md file,but i click `[[MTT6.828]]`  foam created two files `mit6828.md` and  `MIT6.828.md`. also Graph and Backlinking not work.

**Additional information**
![image](https://user-images.githubusercontent.com/22260242/122174214-1dd78c80-ceb5-11eb-8fff-13b8450243b2.png)

**Comment by riccardoferretti** [comment] 2021-06-18 15:24
duplicate of #672

**Closed by riccardoferretti** 2021-06-18 15:24 UTC
Labels: bug
