### ISSUE TITLE
Two files created in a wikilink with Capitalization

### ISSUE THREAD

**Issue by dkowis** [foambubble/foam#719] opened 2021-07-14 16:42 UTC
- Foam version: v0.14.0
- Platform: Linux
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo:  Yep
![image](https://user-images.githubusercontent.com/28048/125659396-e1d87383-6570-4b45-9cf4-de892ba31491.png)

**Summary**
When using a capitalized word in the `[[Wiki-Links]]` style link, it creates two files, one that is capitalized, and one that isn't.

**Steps to reproduce**
1. Download the template
2. create a wikilink like `[[A-Test]]`
3. Get two files, one that's lowercase and one that's upper case.
4. Ctrl-Click to follow the link takes you to the lower case one. (it probably should)

**Additional information**
![image](https://user-images.githubusercontent.com/28048/125659866-cd9b5475-3432-48a4-9be5-e64f0f34abc0.png)

**Comment by dkowis** [comment] 2021-07-14 16:52
Had a conversation on discord that brought up https://github.com/foambubble/foam/pull/688, but I am on the latest version, as best as I can tell. Linking them together via a comment, in case that's useful.

**Comment by pderaaij** [comment] 2021-07-14 17:19
@dkowis Could you provide me an overview of enabled extensions? Just want to double-check if something might be interfering. I just tried to replicate it quickly, but don't have the same issues. Am on macOS, though.

**Comment by dkowis** [comment] 2021-07-14 17:50
ooo, if I ended up with two backlinks thing I didn't mean to :(

```
❯ code --list-extensions
aprilandjan.ascii-tree-generator
asciidoctor.asciidoctor-vscode
ban.spellright
eamodio.gitlens
esbenp.prettier-vscode
foam.foam-vscode
hashicorp.terraform
jebbs.plantuml
kortina.vscode-markdown-notes
lunaryorn.fish-ide
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
mushan.vscode-paste-image
naumovs.color-highlight
philipbe.theme-gray-matter
puppet.puppet-vscode
rebornix.ruby
skn0tt.markdown-link-expander
skyapps.fish-vscode
systemticks.c4-dsl-extension
t-nano.markdown-to-confluence-vscode
tchayen.markdown-links
wingrunr21.vscode-ruby
yzhang.markdown-all-in-one
```

**Comment by pderaaij** [comment] 2021-07-14 18:04
Ah, I see `kortina.vscode-markdown-notes` is enabled. That's one I have disabled and when I enable it, it does replicate the behaviour that you are seeing. It was a recommended extension, but I am not certain if it still is or should be. It's actually removed from the template (https://github.com/foambubble/foam-template/commit/ca8ee63cea4a846b3ce0606ff2252c64825ba89f). 

I'd suggest trying things with this extension disabled. If you're happy with how it works, that solves the problem. If you need markdown notes for certain reasons, we'd like to know!

cc @riccardoferretti

**Comment by riccardoferretti** [comment] 2021-07-15 00:14
I will close this as the problem is resolved.
I agree with @pderaaij: @dkowis if you still find reasons to use markdown notes let us know.

What to do with markdown notes and the issues it causes in combination with Foam is for now discussed in #720

**Closed by riccardoferretti** 2021-07-15 00:14 UTC
Labels: bug
