### ISSUE TITLE
Foam backlink sidebar, graph, `cmd+click` broken when certain characters like `()` in path

### ISSUE THREAD

**Issue by joech4n** [foambubble/foam#1043] opened 2022-07-23 05:22 UTC
### Describe the bug

Update a few things are broken when certain characters like `()` in path to the notes directory:

1. Foam backlink section in sidebar (empty)
1. `Foam: Open Graph` broken (it's empty)
1. `cmd+click` on link tries to create new note even if it exists already

### Steps to Reproduce the Bug or Issue

* download foam template and name it "test()"
* open directory "test()" with foam
* open backlinks section in side bar and confirm it doesn't show backlinks
* open foam graph
* repeat by cloning foam template and naming directory "test" without `()` characters

### Expected behavior

As a user, I expected 3 features listed above to work.

### Operating System Version

Mac OS

### Visual Studio Code Version

Version: 1.69.2 Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a

### Additional context

I'm on Foam v0.19.1.

**Comment by riccardoferretti** [comment] 2022-07-26 15:36
duplicate of #923

**Closed by riccardoferretti** 2022-07-26 15:36 UTC
