### ISSUE TITLE
Global note rename

### ISSUE THREAD

**Issue by dmurph** [foambubble/foam#810] opened 2021-11-01 20:09 UTC
Have a way to refactor the workspace to rename the filename of a note & have all wikilinks update.

Example: I keep notes per person. They are currently in files like `email@.md`. I have since realised that, as people leave the company etc, the email is not the best identifier, and I should just be using their name. However, most of my 'people' are like this. I would love a way to rename this file to `Full Name.md`, and have all wikilinks to the old file be updated to the new file.

**Comment by dmurph** [comment] 2021-11-01 20:11
I can definitely accomplish this by doing a single rename then a grep-and-replace command - so probably not 'use-case-blocking' priority. But it would be nice to have. And it might also share code with the solution to issue #809.

**Comment by riccardoferretti** [comment] 2021-11-03 10:10
This feature is on our todo list, I agree it's pretty important and pretty high priority

**Comment by riccardoferretti** [comment] 2021-11-03 10:13
Closing as duplicate of #809

**Closed by riccardoferretti** 2021-11-03 10:13 UTC
Labels: foam-core
