### ISSUE TITLE
Support for piped wikilinks in the graph view

### ISSUE THREAD

**Issue by zcysxy** [foambubble/foam#306] opened 2020-10-29 16:19 UTC
Piped wikilinks like `[[link|disc]]` or `[[link\|disc]]` (piped wikilinks in a table cell) are widely supported and is also supported by Foam when generating bidirectional links. However, nodes for piped wikilinks in the Foam graph view are grey, and they will not lead you to the right notes when Ctrl + click on them. Hope they will also be supported by the Foam graph view.

![image](https://user-images.githubusercontent.com/48207708/97601730-73a21600-1a45-11eb-93e2-943d606c39f3.png)

**Comment by hikerpig** [comment] 2020-11-25 02:08
@riccardoferretti Is there a reason why this is assigned to 0.8.0 and not 0.7.0 ? I can have a try from the master branch if this has no conflicts with other ongoing plans.

**Comment by riccardoferretti** [comment] 2020-11-25 12:49
@hikerpig this requires some changes in the foam model itself, and I wanted it to be part of a bigger refactoring around link parsing and management.
You can have a try and address this specific issue, just be aware that it might be subject to future changes when the refactoring is implemented.
Thoughts?

**Comment by hikerpig** [comment] 2020-11-25 14:11
@riccardoferretti After checking the source code I do realize that this is more than just the dataviz part.
Then I will step aside and wait after the refactoring. Thanks for your work 👍 .

**Comment by ais** [comment] 2021-01-15 17:16
I believe the issue is with `remark-wiki-link` which uses `:` as its default divider. You can confirm this by switching between `:`- and `|`-divided links on the fly.

You can set the divider by passing `aliasDivider:string` to the plugin constructor(? - _unsure of the terminology here_):

https://github.com/foambubble/foam/blob/97e3b20112cc4d53194a11c987a524851111a955/packages/foam-core/src/markdown-provider.ts#L130

`vscode-markdown-notes` has its own parsing but has the `vscodeMarkdownNotes.pipedWikiLinksSeparator` setting. There's a PR to fix this exact issue in tchayen/markdown-links#81.

@riccardoferretti Would these changes be enough to resolve this issue?

**Comment by riccardoferretti** [comment] 2021-01-18 18:15
That approach should work, thanks for rediscovering the PR, I had forgotten about it!
The rendering issue in Jekyll is interesting.

Given this bug is in Jekyll, I don't consider it a blocker to move forward with adding support for aliases in Foam.
The solution is in no way worse that the current status (as a workaround one would just not use an alias in those situations).

Thoughts?

**Comment by ais** [comment] 2021-07-06 21:04
It seems this is now working in v0.13.8.

**Comment by pderaaij** [comment] 2021-07-07 18:16
Yes, this one can be closed @riccardoferretti

**Closed** 2021-07-07 18:38 UTC
Labels: foam-core
