### ISSUE TITLE
Wiki-links not working in the .md preview

### ISSUE THREAD

**Issue by hmuny99** [foambubble/foam#162] opened 2020-07-26 08:53 UTC
After the new update, every time that i save a file, even though in the graph the link between two files is created, in the .md preview it is not detected

![1595753394_grim](https://user-images.githubusercontent.com/28223818/88475209-225a2600-cf2e-11ea-844c-bda0f15c2131.png)

![1595753401_grim](https://user-images.githubusercontent.com/28223818/88475216-28e89d80-cf2e-11ea-9503-95c73d6ec563.png)

I am currently on Arch linux

![1595754786_grim](https://user-images.githubusercontent.com/28223818/88475539-0d32c680-cf31-11ea-84b6-210270634a5b.png)

**Comment by hmuny99** [comment] 2020-07-26 09:31
It seems that this bug is present only with files created using the 0.2 Foam version, if i create a new workspace, everything works properly

**Comment by jevakallio** [comment] 2020-07-26 16:03
@hmuny99 as per our discussion on Discord, this is an issue with Foam not recognising mixed case file names. This is something we are addressing with [link reference definition improvements](https://foambubble.github.io/foam/link-reference-definition-improvements).

Closing this issue to make triage a bit easier, since the root cause fix is being tracked elsewhere!

**Closed** 2020-07-26 16:05 UTC
