### ISSUE TITLE
["BUG"] Show Graph map keys error

### ISSUE THREAD

**Issue by donniep** [foambubble/foam#301] opened 2020-10-28 13:42 UTC
**Describe the bug**

When I execute the Show Graph command I get:
Command 'Foam: Show graph' resulted in an error (Map keys must be unique; "null" is repeated)

**Affected package**

- [ ] `foam-cli`
- [ ] `foam-core`
- [ ] `foam-vscode`
- [ ] `other/meta/???`
Sorry, don't know

**To Reproduce**
1. Go to 'Command Palette'
2. Click on 'Foam: Show graph'
4. See error:
Command 'Foam: Show graph' resulted in an error (Map keys must be unique; "null" is repeated)

**Expected behavior**

A graph to show up
**Screenshots**

**Additional context**

I get this error in both Linux and Mac

**Comment by riccardoferretti** [comment] 2020-10-28 14:05
thanks for reporting this @donniep, I think I know the code that is causing the issue, but I am surprised of how that could be the case. how big is your workspace? any chance to get a reproducible repo to test this on? thanks!

**Comment by donniep** [comment] 2020-10-28 16:14
> thanks for reporting this @donniep, I think I know the code that is causing the issue, but I am surprised of how that could be the case. how big is your workspace? any chance to get a reproducible repo to test this on? thanks!

The repository is years of private notes, so not a reproducible repo, but it’s 68 .md files totaling about 1.1 MB.

**Comment by riccardoferretti** [comment] 2020-10-28 16:29
hi @donniep, I guess I will start by at least suppressing the problem to get the graph working.
I wonder if in your repo there are "unusual" files or links, e.g. files with only special characters, or empty wikilinks, ...

Basically _my guess_ is the problem is happening here:

https://github.com/foambubble/foam/blob/a34842b95722cdbaa86ce07a5549bbf3947208a9/packages/foam-vscode/src/features/dataviz.ts#L50

or

https://github.com/foambubble/foam/blob/a34842b95722cdbaa86ce07a5549bbf3947208a9/packages/foam-vscode/src/features/dataviz.ts#L60

but I am very surprised to see it because the `id` field is the uri/path of the file, and the `link.to` should not be null (at best empty?!?).

If you have any thoughts/ideas please let me know, thanks!

**Comment by riccardoferretti** [comment] 2020-10-28 17:13
@donniep do you have any YAML in your notes? just came across this: https://github.com/eemeli/yaml/issues/3

**Comment by donniep** [comment] 2020-10-28 18:38
> @donniep do you have any YAML in your notes? just came across this: [eemeli/yaml#3](https://github.com/eemeli/yaml/issues/3)

I am not a programmer, but to all your questions, yes, this is a longstanding collection of notes and journals that has been through several iterations of tooling, including org-mode and, most recently, vim-zettelkasten.  There’s YAML in there from both org-mode and vimwiki, which is a dependency of vim-zettelkasten.  The actual [[]] links are consistent, but the older files have no links in them at all, and may or may not have any YAML.  Consider this migration UAT!

**Comment by riccardoferretti** [comment] 2020-10-28 19:12
hi @donniep from the various tests I have done it feels like this is due to the YAML parsing, and not to the graph code.

Let us try another thing: can you run any of the other foam commands?
My guess is that this issue happens whenever the extension is initialized; right now it's the graph command that does it for you, but it might be caused by any other command.
If I am correct, you should see the same error even when running the other commands.

**Comment by donniep** [comment] 2020-10-28 19:39
> hi @donniep from the various tests I have done it feels like this is due to the YAML parsing, and not to the graph code.
> 
> Let us try another thing: can you run any of the other foam commands?
> My guess is that this issue happens whenever the extension is initialized; right now it's the graph command that does it for you, but it might be caused by any other command.
> If I am correct, you should see the same error even when running the other commands.

Mixed bag:  Open Daily Note (which is the only one I had used before trying the new Graph command) and Copy to Clipboard without Brackets both work.  Update Markdown Reference List and Run Janitor do not.

**Comment by riccardoferretti** [comment] 2020-10-28 20:47
thanks @donniep this kinda validates what I was thinking (the commands that work do not use the foam model).
So, in this case I would say the problem is not with the graph but likely with the YAML parsing.

The only thing I would suggest to validate that is stripping the YAML from all files and see if the issue occurs anyways.
But in the meantime I will close the issue, feel free to reopen either this one or a new one if you get a better sense of where the problem is coming from, thanks!

**Closed by riccardoferretti** 2020-10-28 20:47 UTC
Labels: bug

**Comment by donniep** [comment] 2020-10-28 22:23
> thanks @donniep this kinda validates what I was thinking (the commands that work do not use the foam model).
> So, in this case I would say the problem is not with the graph but likely with the YAML parsing.
> 
> The only thing I would suggest to validate that is stripping the YAML from all files and see if the issue occurs anyways.
> But in the meantime I will close the issue, feel free to reopen either this one or a new one if you get a better sense of where the problem is coming from, thanks!

Stripping YAML worked.  If anyone else runs into this barrier, a one-liner FTW: 
`grep -xlrZ -- "---" . | xargs -0 -l sed -i.bak '1 { /^---/ { :a N; /\n---/! ba; d} }'`
